const types = {
    CHANGE_PHONE: '@app/CHANGE_PHONE',
    CHANGE_CONFIRMATION_CODE: '@app/CHANGE_CONFIRMATION_CODE',

    START_PURCHASE: '@app/START_PURCHASE',
    START_PURCHASE_SUCCESS: '@app/START_PURCHASE_SUCCESS',

    CONFIRM_PURCHASE: '@app/CONFIRM_PURCHASE',
    PURCHASE_CONFIRMATION_FAILED: '@app/PURCHASE_CONFIRMATION_FAILED',
    RESEND_CONFIRMATION_CODE: '@app/RESEND_CONFIRMATION_CODE',
    PURCHASE_SUCCESS: '@app/PURCHASE_SUCCESS',
    PURCHASE_FAIL: '@app/PURCHASE_FAIL',

    TIMER_TICK: '@app/TIMER_TICK',
    TIMER_END: '@app/TIMER_END',

    CANCEL_PURCHASE: '@app/CANCEL_PURCHASE',
    RESET: '@app/RESET',
};

export default types;
