export const STEP = {
    PHONE_ADDITION: 'PHONE_ADDITION',
    CONFIRMATION: 'CONFIRMATION',
    SUCCESS: 'SUCCESS',
    FAIL: 'FAIL',
};

export const PURCHASE_STATUS = {
    NONE: 'NONE',
    AWAIT_CONFIRMATION: 'AWAIT_CONFIRMATION',
    SUCCEEDED: 'SUCCEEDED',
    FAILED: 'FAILED',
};